name: Build Zen Browser .deb Package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget xz-utils dpkg-dev jq

      - name: Build .deb package
        run: |
          git clone https://github.com/huanhoahongso3-collab/zen-browser-debian.git
          cd zen-browser-debian
          wget https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-x86_64.tar.xz

          set -euo pipefail
          REPO="zen-browser/desktop"
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
          CLEAN_VERSION=${LATEST_VERSION#v}

          PACKAGE_NAME="zen-browser"
          VERSION=$CLEAN_VERSION
          ARCH="amd64"
          BUILD_DIR="${PACKAGE_NAME}_${VERSION}"
          INSTALL_DIR="$BUILD_DIR/opt/zen"
          BIN_DIR="$BUILD_DIR/usr/local/bin"
          DESKTOP_DIR="$BUILD_DIR/usr/local/share/applications"
          ICON_BASE="$BUILD_DIR/usr/share/icons/hicolor"
          TARBALL="zen.linux-x86_64.tar.xz"

          rm -rf "$BUILD_DIR"
          mkdir -p "$INSTALL_DIR" "$BIN_DIR" "$DESKTOP_DIR"

          tar -xf "$TARBALL"
          mv zen/* "$INSTALL_DIR"

          cat > "$BIN_DIR/zen" <<EOF
#!/bin/bash
/opt/zen/zen "\$@"
EOF
          chmod +x "$BIN_DIR/zen"

          for size in 16 32 48 64 128; do
            mkdir -p "$ICON_BASE/${size}x${size}/apps"
            cp "$INSTALL_DIR/browser/chrome/icons/default/default${size}.png" "$ICON_BASE/${size}x${size}/apps/zen.png"
          done

          cat > "$DESKTOP_DIR/zen.desktop" <<EOF
[Desktop Entry]
Name=Zen Browser
Comment=Experience tranquillity while browsing the web without people tracking you!
Exec=/opt/zen/zen %u
Icon=zen
Terminal=false
StartupNotify=true
Type=Application
MimeType=text/html;x-scheme-handler/http;x-scheme-handler/https;
Categories=Network;WebBrowser;
EOF

          mkdir -p "$BUILD_DIR/DEBIAN"
          cat > "$BUILD_DIR/DEBIAN/control" <<EOF
Package: $PACKAGE_NAME
Version: $VERSION
Section: web
Priority: optional
Architecture: $ARCH
Maintainer: huanhoahongso3
Description: Zen Browser - A privacy-focused browser that helps you browse in peace.
EOF

          cat > "$BUILD_DIR/DEBIAN/postinst" <<'EOF'
#!/bin/bash
set -e
if command -v gtk-update-icon-cache &>/dev/null; then
  gtk-update-icon-cache -f /usr/share/icons/hicolor
fi
EOF
          chmod +x "$BUILD_DIR/DEBIAN/postinst"

          dpkg-deb --build "$BUILD_DIR"
          mv "${BUILD_DIR}.deb" .

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: zen-browser-deb
          path: zen-browser-debian/*.deb
